### PR TITLE
Changed URL config + added s1 pos rec to __init__

### PR DESCRIPTION
**Pull request by LuisSanchez25**
_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

### CODE REVIEW

**Comment by dachengx** [comment]
Considering the merged https://github.com/XENONnT/straxen/pull/1146, are we going to close this PR?

**Comment by dachengx** [comment]
@matteoguida Sorry, I can not understand the current condition. At https://github.com/XENONnT/straxen/blob/0c3443d62c465b827e9d4e5ab5113127473a0c58/straxen/plugins/peaks/peak_s1_position_cnn.py#L19 you are already using `straxen.URLConfig`. And the auto-test gives no error. Would you show me the error? Also I think I saw Luis approved the PR but maybe then retrieved it...

**Comment by matteoguida** [comment]
@dachengx I open an [issue](https://github.com/XENONnT/straxen/issues/1157), @LuisSanchez25 missclicked when I approved the PR as I wrote [here](https://github.com/XENONnT/straxen/pull/1146#pullrequestreview-1378528980) in a message (we were both trying to understand what the problem was).

**Comment by matteoguida** [comment]
As we solved all the issues I guess this PR can be closed, thanks a lot guys for the great support!

**Pull request closed without merging**
