### PR TITLE
Set shadow plugins as SaveWhen.ALWAYS

### PR DESCRIPTION
**Pull request by dachengx**
## What does the code in this PR do / what does it improve?

This PR suggests setting PeakShadow and EventShadow plugin as `strax.SaveWhen.ALWAYS`. Additionally, set `infer_type` explicitly. 

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [x] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### CODE REVIEW

**Review by WenzDaniel — COMMENTED** [review]
Why do you always have to save it? I understood that computation would be rather quick. 

In addition can you please set the proper types of your options? Setting infer_type to false was just a quick and dirty solution for all other plugins as Yossi fixed a bug in strax's type checking. You can set the type by adding `type=str` or `type=(int, float)` etc. to your options.

**Comment by WenzDaniel** [comment]
* save_when.EXPLICIT means that you still can save the data if you call make like `st.make(run_id, data_type, save=(data_type,))`

**Comment by dachengx** [comment]
> Why do you always have to save it? I understood that computation would be rather quick.
> 
> In addition can you please set the proper types of your options? Setting infer_type to false was just a quick and dirty solution for all other plugins as Yossi fixed a bug in strax's type checking. You can set the type by adding `type=str` or `type=(int, float)` etc. to your options.

- The reason for saving shadow variables during reprocessing is to save time for analysts when they want to implement shadow cut and shadow distance cut. This strategy is similar to `event_pattern_fit` and its related cuts. 
- Yes, I will set the proper type to these options.

**Comment by JoranAngevaare** [comment]
> > Why do you always have to save it? I understood that computation would be rather quick.
> > In addition can you please set the proper types of your options? Setting infer_type to false was just a quick and dirty solution for all other plugins as Yossi fixed a bug in strax's type checking. You can set the type by adding `type=str` or `type=(int, float)` etc. to your options.
> 
>     * The reason for saving shadow variables during reprocessing is to save time for analysts when they want to implement shadow cut and shadow distance cut. This strategy is similar to `event_pattern_fit` and its related cuts.
> 
>     * Yes, I will set the proper type to these options.

Hi @dachengx , thanks, do you have the numbers for a typical run? If I recall correctly, this was O (minutes) for (event_pattern_fit) and O seconds for EventShadow but it might be good to check and compare.

Small note this discussion is fully about code so can be perfectly held on github 😉

**Comment by dachengx** [comment]
> > > Why do you always have to save it? I understood that computation would be rather quick.
> > > In addition can you please set the proper types of your options? Setting infer_type to false was just a quick and dirty solution for all other plugins as Yossi fixed a bug in strax's type checking. You can set the type by adding `type=str` or `type=(int, float)` etc. to your options.
> > 
> > 
> > ```
> > * The reason for saving shadow variables during reprocessing is to save time for analysts when they want to implement shadow cut and shadow distance cut. This strategy is similar to `event_pattern_fit` and its related cuts.
> > 
> > * Yes, I will set the proper type to these options.
> > ```
> 
> Hi @dachengx , thanks, do you have the numbers for a typical run? If I recall correctly, this was O (minutes) for event_pattern_fit and O (seconds) for EventShadow but it might be good to check and compare.
> 
> Small note this discussion is fully about code so can be perfectly held on github 😉

Sorry for the late reply. I checked 10 bkg runs and 10 radon runs which are all ~30min. For bkg run, the average time consumption is ~2min, while for radon runs, ~7min.

**Comment by skazama** [comment]
@dachengx Thanks Dacheng, as you said above it took significant amount of time to use shadow cut for Rn220 ER-leakage studies (me and @jingqiangye ), so it's nice if we can keep these plugins like event_pattern_fit. @JoranAngevaare Do you think the time Dacheng sent above is reasonable?

**Review by JoranAngevaare — CHANGES_REQUESTED** [review]
@skazama @dachengx sorry, I did not pay full attention to https://github.com/XENONnT/straxen/pull/753 but these processing times are __really__ long. 

Let me open a PR to fix this because this plugin shouldn't be this is so slow

**Comment by WenzDaniel** [comment]
Closed due to https://github.com/XENONnT/straxen/pull/806

**Pull request closed without merging**
