### PR TITLE
Add coveralls to travis

### PR DESCRIPTION
**Pull request by jorana**
**What is the problem / what does the code in this PR do**
Add https://docs.coveralls.io/ to travis testing.

**Can you briefly describe how it works?**
Just like in strax

**My concern**
I'm just copy pasting code here. I have added coveralls for straxen: https://coveralls.io/github/XENONnT/straxen, however I'm not sure if this is going to work the first time. If someone is willing to give me the green light I can just push to master.

I think this would be great to add because it shows how good/bad your PR is and increases the incentive to write tests.

### CODE REVIEW

**Comment by jorana** [comment]
@WenzDaniel , are we running into https://github.com/AxFoundation/strax/issues/328 at line https://github.com/AxFoundation/strax/blob/master/strax/processing/pulse_processing.py#L116?\

This just happens for numbaless coverage (newly added in this PR) so you probably have never seen it before.

afbeelding

**Comment by WenzDaniel** [comment]
This is interesting, but no the Issue you are linking would be the opposite I think. Back then I had the issue that my assignment 
```
data = thing['data'][thing['length']]
```
was a view onto `thing['data']`. Hence when I modified data, I indirectly modified thing['data'] which was not desired. Hence this read-only thing you are describing here would have saved me from this issue. 
I know that one can make an array immutable via `array.flag.writeable = False`, but I do not think that we are explicitly doing this somewhere. Further, I checked the requirements since v0.12.0 and numpy and numba has not change since then. Have you updated your env recently?

**Comment by WenzDaniel** [comment]
The thing I do not understand though, why is it just popping up for the nveto_recorder?

**Comment by jorana** [comment]
Thanks @WenzDaniel , trying to work from here now

**Comment by jorana** [comment]
Ok, seems to work :) @ershockley or @WenzDaniel willing to review (is just technical so might do without)

**Comment by jorana** [comment]
Ok, changed the way it looks at the package, it's now at 61 percent (apparently this test_plugins is very effective). I will continue and merge.

**Pull request merged**
