### PR TITLE
Patch he names

### PR DESCRIPTION
**Pull request by WenzDaniel**
**What is the problem / what does the code in this PR do**
Explicitly call high energy Plugins ...HighEnergy instead of ...HE

### CODE REVIEW

**Comment by jorana** [comment]
Hi Daniel, in principle looks fine. Will test it on Monday if we don’t change anything unintendedly. 

Also in d951245  I added a small preamble for all HE plugins. I assume you are fine with that.

**Comment by jorana** [comment]
@WenzDaniel I just checked and I don't see any problems. I think we do need approve of @feigaodm as the lineage of ``records_he``  and beyond changes. @feigaodm, if we change this now (for readability) we need to reprocess the following plugins:
afbeelding

**Review by jorana — APPROVED** [review]
Software wise it looks completely fine. The lineage changes hence I think the merge approval should be an ACs call.

**Comment by feigaodm** [comment]
Thanks @WenzDaniel and @jorana , it looks fine to me. I guess we will need to reprocess every run when this is merged. So far I see everything from normal and HE boards are separately processed and analyzed. We shall think about how can we connect the two together nicely, but this might be more natural when we have good S2s, especially when it's related to positions. These comments are not directly related to this PR though, but I want to put it here as a reminder for us ;-)

**Review by feigaodm — APPROVED** [review]

**Pull request merged**
