### PR TITLE
use gw at the DAQ

### PR DESCRIPTION
**Pull request by jorana**
**What is the problem / what does the code in this PR do**
Use gw as the host for mongo on the DAQ.

Also see the discussion here:
https://xenonnt.slack.com/archives/C016UJZ090B/p1604669100226800

### CODE REVIEW

**Review by darrylmasson — APPROVED** [review]
I'm seeing real benefit in a `config.ini` or equivalent so we don't end up version-bumping for "trivial" changes like database addresses.

**Comment by jorana** [comment]
yeah I guess we are waiting until Evan labels this one ready https://github.com/XENONnT/straxen/pull/163

**Comment by tunnell** [comment]
You can use the corrections system too.  Just make some variable called 'daq_rundb_address' then put it in ONLINE.  The corrections system is a time dependent INI file, where the ONLINE collection is just a normal ini for strings.

**Comment by tunnell** [comment]
@ahiguera-mx see my comment about ini

**Comment by jorana** [comment]
@tunnell I'm not sure if I see the point, you still need access to the database before. For reading a simple file, we might as well use Admix # 163

**Comment by tunnell** [comment]
Just the same machinery so only one configuration thing.  And track.

**Comment by darrylmasson** [comment]
You can't store the database access information in the database and expect it to be useful. This is like locking your keys in the car and then asking why you're having trouble starting the engine. Also tracking this info seems pointless, we don't care what the address _was_, we only care what it is right now.

**Comment by ershockley** [comment]
I agree the utilix config would solve this. I will work on that PR today

**Comment by ahiguera-mx** [comment]
> @ahiguera-mx see my comment about ini

**Pull request merged**
