### PR TITLE
test python 3.9

### PR DESCRIPTION
**Pull request by jorana**
**What is the problem / what does the code in this PR do**
With [numba 0.53](https://numba.readthedocs.io/en/stable/release-notes.html#version-0-53-0-11-march-2021) we can support python3.9 🎉 !

### CODE REVIEW

**Comment by jorana** [comment]
:tada: too soon. I always thought that numba was the limiting factor, but it's tensorflow.

**Comment by jorana** [comment]
TensorFlow 2.5 actually should be supported for py3.9. Let's try again!

**Review by WenzDaniel — APPROVED** [review]
I do not see any reason why we should not add it to the tests. Just to be sure we are on the same page, now we are testing things without tensorflow, are not we?

**Comment by jorana** [comment]
@WenzDaniel , ah no for sure not. We are testing **with** tensorflow. I just removed it from the list of pinned versions which we grep from https://github.com/XENONnT/base_environment/blob/master/requirements.txt since tensorflow 2.5 is needed for python 3.9. However, that is not the version provided in the base environment. Therefore, we just let pip resolve a version of tensorflow we can use.

**Comment by jorana** [comment]
> 
> 
> I do not see any reason why we should not add it to the tests. Just to be sure we are on the same page, now we are testing things without tensorflow, are not we? Where are we now loading tensorflow 2.5?

@WenzDaniel , this is now done in the setup.py test:
https://github.com/XENONnT/straxen/pull/407/checks?check_run_id=2455414942#step:8:92

**Pull request merged**
