### PR TITLE
Add perpendicular wires handling info and function

### PR DESCRIPTION
**Pull request by ricmperes**
## What does the code in this PR do / what does it improve?
  * Include easy to access perpendicular wires info: rotation angle in relation to standard x axis and x position on the rotated plane (vertical perpendicular wires).
  * Add function to convert from standard (x,y) to (x_rotated, y_rotated), where in the rotated plane the perpendicular wires are vertically aligned.
## Can you briefly describe how it works?
  - Defines the useful variables `perp_wire_angle ` and `perp_wire_x_rot_pos ` for easy access on plugins, cuts and analysis.
  - Defines the function `rotate_perp_wires(x_obs, y_obs)` which rotates the x,y plane to make the perpendicular wires parallel to the y-axis. Takes x and y values (both flt, np arrays or pd series) and returns the corresponding values for rotated x and rotated y.
## Can you give a minimal working example (or illustrate with a figure)?
```fake_x_obs = np.linspace(-10,10,100)
fake_y_right_obs = np.tan(np.deg2rad(60))*fake_x_obs-5
fake_y_left_obs = np.tan(np.deg2rad(60))*fake_x_obs+5

fake_x_rot_right,fake_y_rot_right = rotate_perp_wires(fake_x_obs, fake_y_right_obs)
fake_x_rot_left, fake_y_rot_left = rotate_perp_wires(fake_x_obs, fake_y_left_obs)
```
rotated_coordinates_perp_wires_pr

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

### CODE REVIEW

**Review by WenzDaniel — APPROVED** [review]
Thanks a lot. Looks good to me.

**Comment by cfuselli** [comment]
Nice! It would also be very useful to me to have an option to rotate of another 90° to have the perpendicular wires parallel to the x-axis!

**Comment by ricmperes** [comment]
> Nice! It would also be very useful to me to have an option to rotate of another 90° to have the perpendicular wires parallel to the x-axis!

Hey, @cfuselli ! Easy enough, you can now use `angle_extra = -90` (or any other angle in degrees) to add to the rotation.
rotated_coordinates_perp_wires_pr_90

**Comment by ershockley** [comment]
@ricmperes I think this is fine, but remember this is a public repo so we should not be putting too many nT-specific numbers in straxen. I would have preferred to keep this in cutax.

**Comment by WenzDaniel** [comment]
I think the information that we use meshes and they might be oriented differently than our coordinate system is not really sensitive information.

**Pull request merged**
