### PR TITLE
add more tests to straxen

### PR DESCRIPTION
**Pull request by jorana**
**What is the problem / what does the code in this PR do**
Add several tests for packages missed by the current tests.

**Can you briefly describe how it works?**
Mostly checks that things load properly.

### CODE REVIEW

**Comment by jorana** [comment]
2.5 % coverage increase of tests over entire straxen code. Not too bad..

**Comment by WenzDaniel** [comment]
Hej, I am not sure if I should already review this PR. One question/suggestion, do you think it make sense to add for example for `test_straxen` some "truth" dictionary containing the expected outcomes. I am asking in case we will ever change the demo it might be easier to just modify the dict instead of tests itself.

**Comment by jorana** [comment]
Sure, you mean like testing the number of events and so on? Could add with some reasonable error or margin. Thanks for the sugestion

**Comment by jorana** [comment]
@WenzDaniel Done, can you re-review?

**Pull request merged**
