### PR TITLE
use channel tight coincidence level

### PR DESCRIPTION
**Pull request by JoranAngevaare**
## What does the code in this PR do / what does it improve?
Change the tight coincidence parameter used in the peaklet classification

## Alternatives
We could also revert https://github.com/XENONnT/straxen/pull/691 since it might probably be more confusing to keep two parameters around

### CODE REVIEW

**Review by WenzDaniel — APPROVED** [review]
Thanks

**Comment by ershockley** [comment]
@JoranAngevaare @WenzDaniel Are we waiting on anything else for this one?

**Comment by WenzDaniel** [comment]
Yes, as discussed within the Team-Leader channel I would like to rename things. `tight_coincidence -> tight_coincidence_hits` and `tight_coincidence_channel -> tight_coincidence` (at least I had the impression that we converged on this one see https://app.slack.com/client/T01602WL334/G01DGC77CAW/thread/G01DGC77CAW-1637223273.020600). But this requires reprocessing `>= peaklets`. So I would like to wait for `global_v6`.

**Comment by WenzDaniel** [comment]
I am also wondering, if we should not wait in general with all the PRs which change the lineage till the end. Might be that some analysts would like to use a certain bug fix or patch which is already merged with master.

**Comment by ershockley** [comment]
Ah right, agreed. THanks!

**Pull request merged**
