### PR TITLE
Debug for `EventwBayesClass` because peaks overlapping

### PR DESCRIPTION
**Pull request by dachengx**
_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

Debug `EventwBayesClass`. In very rare cases the peaks' `"time"` can be the same, so simply use the matching between time https://github.com/XENONnT/straxen/blob/c61848018f2fd49504e6d3b50de1343ecfb056b0/straxen/plugins/events/event_w_bayes_class.py#L29-L30 can cause error like:
```
CRITICAL:ThreadedMailboxProcessor:Target Mailbox (event_w_bayes_class_paired) killed, exception <class 'strax.mailbox.MailboxKilled'>, message (<class 'ValueError'>, ValueError('NumPy boolean array indexing assignment cannot assign 48003 input values to the 47986 output values where the mask is true'), <traceback object at 0x7f62537a4e00>)
```

## Can you briefly describe how it works?

Mimicking what `EventAmbience` does, split the peaks for each event and assign the fields based on indices: https://github.com/XENONnT/straxen/blob/c61848018f2fd49504e6d3b50de1343ecfb056b0/straxen/plugins/events/event_ambience.py#L42-L57.

The results are not changed so I will not update the `__version__`.

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

### CODE REVIEW

**Comment by dachengx** [comment]
However, this plugin is not widely used.

**Comment by WenzDaniel** [comment]
I am wondering whether we should not remove this plugin. Is it still being maintained? I do not think so.

**Comment by dachengx** [comment]
> I am wondering whether we should not remove this plugin. Is it still being maintained? I do not think so.

For the reproducibility of old results, we still need it. I think we can keep it for a while.

**Comment by WenzDaniel** [comment]
Old results use old container no? Otherwise it is not reproducible anyhow?

**Comment by dachengx** [comment]
> Old results use old container no? Otherwise it is not reproducible anyhow?

Yes. You are right. I mean the reproducibility of the codes in other repo which still uses this plugin.

**Review by MerzJohannes — APPROVED** [review]
Looks good to me. If we want to keep it for reproducibility we can merge it.

**Review by yuema137 — APPROVED** [review]
In the previous code, `mask` may have a larger length than `mask_ev` (and `events`) when there are duplicated 'time' in `peaks`. The PR fixes this problem by looping over split peaks together with events, and only assigning the probability when a valid peak index is found.  It looks good to me.

**Pull request merged**
