### PR TITLE
Faster bootstrax queries for new runs

### PR DESCRIPTION
**Pull request by darrylmasson**
**What is the problem / what does the code in this PR do**

The `$exists` query operator in MongoDB is slow because it can't be satisfied in the usual `log(n)` time as a standard indexed query. As the runs database continues to grow in size inefficient queries will rapidly get slower and slower. Also, bootstrax should get patched to match https://github.com/coderdj/redax/pull/109

**Can you briefly describe how it works?**

Rather than continue to use slow operators, a minor change in the DB schema allows for more efficient index usage.

This partially implements #269, depending on the scope of changes necessary

### CODE REVIEW

**Comment by jorana** [comment]
Hi Darryl, thanks for starting this PR, I have a branch somewhere that started on this as well after we had our discussion. Glad to see you had the time to add this to redax. Let me open a PR after this to merge the branch I had started too.

**Review by jorana — APPROVED** [review]
Looks good

**Comment by darrylmasson** [comment]
Scooped!

I'm just trying to clean up remaining loose ends in redax before we change repositories

**Comment by darrylmasson** [comment]
We'll have to synchronize the deployment, but that's relatively trivial

**Comment by jorana** [comment]
Just let me know when you are doing the new deployment I can do straxen accordingly.

**Pull request merged**
