### PR TITLE
Fix leading zeros error

### PR DESCRIPTION
**Pull request by jmosbacher**
_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?
Passing a literal URL parameter e.g. run_id with leading zeros e.g. 'cmt://elife?version=v1&run_id=026000' can raise a syntax error when its parsed by URLConfig. Currently you would have to drop the leading zeros or explicitly mark the value as a string using quotes. The PR changes the parsing behavior so that zero-padded numbers will be parsed as strings.

## Can you briefly describe how it works?
Ignores SyntaxError exceptions when parsing config values using pythons builtin literal_eval

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Any idea why this leads to a coverage decrease of 11%?

**Comment by JoranAngevaare** [comment]
> Any idea why this leads to a coverage decrease of 11%?

Yeah it's because this PR is from a remote fork

**Comment by jmosbacher** [comment]
Oh right, I forgot about the request to use origin branches instead of forked ones...

**Review by JoranAngevaare — COMMENTED** [review]
maybe good to add a few comments to `parse_val`. I'm not entirely sure what will happen with your example here, maybe we can add a test for it? Because dropping the leading 0 silently from a run_id is an easy way to get confusing errors when loading data etc.

**Comment by jmosbacher** [comment]
@JoranAngevaare good point, i should add a test. 
Just FYI, this PR is meant to avoid needing to drop the leading zeros. Currently, if there is a leading zero in one of the URL params, you will get a SyntaxError from python literal_eval to avoid this error you would have to pass the run_id in the URL without the leading zero. This PR ignores this SyntaxError so the e.g run_id will be parsed as a string and include the leading zeros.

**Review by JoranAngevaare — APPROVED** [review]
Nice!

**Pull request merged**
