### PR TITLE
Update definition of the SE density

### PR DESCRIPTION
**Pull request by chnlkx**
_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

Update the se_density calculated for the hotspot veto cut to use a score based on the distance and position reconstruction resolution.

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

### CODE REVIEW

**Comment by chnlkx** [comment]
Hi @dachengx and @yuema137, I have a question: this plugin depends on the ''peak_position'' in v2.2.5. So how should we proceed properly?

**Comment by yuema137** [comment]
@chnlkx Thanks for this PR. `peak_positions` is a merge-only plugin, and what it does is just to select the positions computed with different algorithms. So if you want to make sure that your plugin depends on the `mlp` one you can just use that directly. But in principle there should be be substantial difference when we use different position reconstruction algorithms and the result should be consistent.

**Comment by dachengx** [comment]
> @chnlkx Thanks for this PR. `peak_positions` is a merge-only plugin, and what it does is just to select the positions computed with different algorithms. So if you want to make sure that your plugin depends on the `mlp` one you can just use that directly. But in principle there should not be substantial difference when we use different position reconstruction algorithms and the result should be consistent.

https://xenonnt.slack.com/archives/C016UJZ090B/p1726239673345349

**Comment by yuema137** [comment]
@dachengx Thanks dacheng. This is for sure a much better practice. We should separate the developments as some low level plugins are frozen and will not be reprocessed. Should we update the readme and somehow make an annoucement?

**Comment by dachengx** [comment]
> @dachengx Thanks dacheng. This is for sure a much better practice. We should separate the developments as some low level plugins are frozen and will not be reprocessed. Should we update the readme and somehow make an annoucement?

You are right. I think this decision is for people in XENONnT collaboration so modification of `README.md` is not really needed.

**Comment by yuema137** [comment]
Submission to the correct branch is in #1427

**Pull request closed without merging**
