### PR TITLE
Add a few special cases

### PR DESCRIPTION
**Pull request by jjakob03**
The renaming for variables starting with cs1/cs2 is made via explicitly written special cases. Those were not updated for a few added fields. 
See https://straxen.readthedocs.io/en/latest/reference/datastructure_nT.html#event-info-double

### CODE REVIEW

**Review by JoranAngevaare — CHANGES_REQUESTED** [review]
Thanks @jjakob03 ! Indeed, let's do add these.

Could you increment the version of the plugin such that we know the code changed?

**Comment by jjakob03** [comment]
Hey @JoranAngevaare, I always guessed so, but actually I do not know for sure. Probably @DonNabla knows more. I just added a space in these two lines for conformity.

**Review by JoranAngevaare — APPROVED** [review]

**Comment by JoranAngevaare** [comment]
> 
> 
> Hey @JoranAngevaare, I always guessed so, but actually I do not know for sure. Probably @DonNabla knows more. I just added a space in these two lines for conformity.

Right, sometimes github tricks me in believing these lines are new whereas they are not really 😉 . Thanks, yeah let's certainly not change it when it has always been like this (still interested though)..

Thanks again, as far as I'm concerned, we can merge

**Comment by DonNabla** [comment]
Hello, the name `ds_s1_dt` is an old notation, which could be indeed renamed: S1_delay_time. But a lot of people are used to ds_s1_dt, and are doing analysis based on this name, not sure if it is really necessary to change the name. (for me it would be like rename cS1 into cor_S1) :)

**Comment by JoranAngevaare** [comment]
@DonNabla , definitely let's not break things just because they confuse me :wink: thanks for explaining!

**Pull request merged**
