### PR TITLE
Exclude S1 as triggering peak

### PR DESCRIPTION
**Pull request by WenzDaniel**
## What does the code in this PR do / what does it improve?
With this PR we exclude S1 signals from being triggering peaks. Due to the insufficient right extension. See also this [figure](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenonnt%3Awenz%3Acomissioning%3Atpc%3Agatti_filter&media=xenon:xenonnt:wenz:comissioning:tpc:gatti_filter:z_versus_area_wo_fiducial_volume.png).

### CODE REVIEW

**Review by skazama — APPROVED** [review]
@WenzDaniel Thanks for the PR. It looks fine to me.

**Comment by JoranAngevaare** [comment]
> ## What does the code in this PR do / what does it improve?
> 
> With this PR we exclude S1 signals from being triggering peaks. Due to the insufficient right extension. See also this [figure](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenonnt%3Awenz%3Acomissioning%3Atpc%3Agatti_filter&media=xenon:xenonnt:wenz:comissioning:tpc:gatti_filter:z_versus_area_wo_fiducial_volume.png).

@WenzDaniel could you explain a bit more or link the note this belongs to, I don't immediately see it.

But yeah overall I think this is fine, we discussed this ages ago with @jpienaar13 but I don't recall why there was reluctance at the time to not do this. Maybe @jingqiangye remembers?

**Comment by skazama** [comment]
@WenzDaniel I think we all agreed to approve this PR, but it seems that there is a conflict. Can you please resolve that?

**Comment by WenzDaniel** [comment]
Sure, can do I would not merge it till making the new release though.

**Comment by jingqiangye** [comment]
I think @jpienaar13  was reluctant to further shorten the right extension but didn't oppose disabling s1 from triggering? Correct me if I am wrong...

But yeah I also agree with this change.

**Review by zhut19 — APPROVED** [review]

**Pull request merged**
