### PR TITLE
Itp test

### PR DESCRIPTION
**Pull request by JoranAngevaare**
Add a test that fails:
https://github.com/XENONnT/base_environment/runs/4483785976?check_suite_focus=true

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Okay I reverted https://github.com/XENONnT/straxen/pull/757 feel free to merge it again with master to see if the test passes now. Can merge afterwards.

**Comment by JoranAngevaare** [comment]
@WenzDaniel thanks, actually I would like to see this test fail. I also feel like we should have a few extra test for this function. This test is the bare minimum of course 😉

**Comment by WenzDaniel** [comment]
The current ones running should fail hopefully :D

**Comment by JoranAngevaare** [comment]
okay, they just did, I'm updating with master now and merge if they succeed now

**Comment by zhut19** [comment]
Hi, @JoranAngevaare I think it is caused by one of my mistakes, a typo in the s2 correction causing a metadata field to be considered as a map. I will change the file later but I think it has been excluded from default tests since https://github.com/XENONnT/private_nt_aux_files/pull/129, so the test should pass now.

**Comment by JoranAngevaare** [comment]
@zhut19 , ah okay, good to know thanks for fixing it, I guess fixing the map is one method.

I did see this issue later than https://github.com/XENONnT/private_nt_aux_files/pull/129 (I think) but okay, if you are fixing the map, there is no issue :)

**Pull request merged**
