### PR TITLE
Explicitly set infer_dtype=False for all Options

### PR DESCRIPTION
**Pull request by jmosbacher**
Due to a bug fixed in strax PR [#569](https://github.com/AxFoundation/strax/pull/569) many config options in straxen will now produce warnings. This PR suppresses these warning by explicitly setting the infer_dtype to False wherever the type of the config Option would have been inferred from the default value in the future.
This breaks backward compatibility with older strax versions since the infer_dtype keyword did not exist before, so not sure this is the best way to suppress these warnings. Maybe a better option would be to have a global setting in strax that suppresses them. Its open for discussion, but the PR is here in case we decide to use it.

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Looks fine to me. We can updated the individual option whenever we change something else. I think for most of the int/float options you could also set it already to true. Btw I also noticed that you forgot to updated the doc-string here: https://github.com/AxFoundation/strax/blob/d23a605ab8171d89209aeb10f9d2f86b456a212e/strax/config.py#L66

**Comment by jmosbacher** [comment]
@WenzDaniel Indeed you are correct! I also realized when adding the docstring that infer_dtype is a bit misleading and renamed it to infer_type in this [draft](https://github.com/AxFoundation/strax/pull/587). Until that is resolved, ill convert this to a draft.

**Comment by JoranAngevaare** [comment]
Thanks @jmosbacher , let's merge sooner rather than later to prevent conflicts, I don't see any issue with this 👍

**Review by JoranAngevaare — APPROVED** [review]

**Comment by WenzDaniel** [comment]
Any idea why it is just failing for this DAQReader option. I cannot spot the mistake.

**Comment by jmosbacher** [comment]
@WenzDaniel I think the installation test is done with the latest version of strax and not master right? so wouldn't expect it to succeed

**Comment by JoranAngevaare** [comment]
@jmosbacher maybe we should also do this on WFSim, the logs also contain quite a few warnings there.

**Comment by jmosbacher** [comment]
Good point, ok ill take a look at the WFSim code

**Comment by JoranAngevaare** [comment]
@jmosbacher we are also going to have some fun in cutax

**Comment by JoranAngevaare** [comment]
@jmosbacher I'm merging this for now, although I still fill feel inclined to just not type-check options but I want to get a release out.

**Pull request merged**
