### PR TITLE
Gain mini analysis

### PR DESCRIPTION
**Pull request by GiovanniVolta**
I have modified _mini_analysis.py_ in order to let it works with 2 runs for the LED calibration. I have added also the actual gain mini analisys. I have tested and it works. 
Here _/dali/lgrandi/led_calibration/Script_ there are a the shifter's script (working) prototype for XENONnT gain. 
A small explanation on how it works: 
- the shifter has just to modifi the date and the run ids in the configuration file and submit the job. The data will automatically saved on dali and pushed on the database. This last part is not implemented yet.

I would like to upload these scripts on github but I am not sure where, could you point my the right place?

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Dear @GiovanniVolta may I recommend to check the issues found by CodeFactor before anyone starts a larger review. Just click on the details button. CodeFactor helps us to keep the code clean and readable.

**Comment by GiovanniVolta** [comment]
> 
> 
> Dear @GiovanniVolta may I recommend to check the issues found by CodeFactor before anyone starts a larger review. Just click on the details button. CodeFactor helps us to keep the code clean and readable.

Hi Daniel, you are compleatly right. Indeed it will remove the pull request. It is definetly not ready for the review

**Comment by WenzDaniel** [comment]
@GiovanniVolta you do not have to close the PR. You can continue updating it. If you have any questions regarding CodeFactor let us know.

**Comment by jorana** [comment]
> 
> 
> @GiovanniVolta you do not have to close the PR. You can continue updating it. If you have any questions regarding CodeFactor let us know.

Both are options. However it sometimes makes more sense to open a new PR because otherwise you'd have to plow through a PR of >20 commits which is not always the clearest (I'm not a particular fan of this especially as it makes the commit history quite chaotic) . 

@GiovanniVolta if I can make one more suggestion. Rather than altering the minianalysis to be able to take multiple runs you could also make use of a superrun (https://strax.readthedocs.io/en/latest/advanced/superrun.html). This makes things a lot easier as we don't have to worry that we have a backwards compatible version of the minianalysis.

**Comment by jorana** [comment]
@GiovanniVolta , can you perhaps give an update if you are still working on this?

**Comment by GiovanniVolta** [comment]
> 
> 
> @GiovanniVolta , can you perhaps give an update if you are still working on this?

Hi Joran, no I am not! I can actually delete it, I think it is not necessary anymore

**Comment by jorana** [comment]
Thanks, I'll close the PR for now, feel free to revive your branch anytime.

**Pull request closed without merging**
