### PR TITLE
Remove Shadow&Ambience plugin SaveWhen.EXPLICIT

### PR DESCRIPTION
**Pull request by dachengx**
## What does the code in this PR do / what does it improve?

Remove `save_when` attribute of `PeakShadow`, `EventShadow`, `PeakAmbience`, `EventAmbience` plugins. 

Motivation: When analysts are loading `event_shadow` of calibration data, the `save_when = strax.SaveWhen.EXPLICIT` `PeakShadow` plugins will be stored in RAM and RAM can not hold that large amount of data. 

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [x] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Can you please be a bit more specific and give an example? Because, if you load all data it does not make any difference if it is first stored to disk. Further, I am wondering how you can run into any RAM issues. All the data_types you are using are small. Could it  be that for one of the runs `peak_basics` were not available so you started making `peaks` first?

**Comment by ershockley** [comment]
If you check e.g. run 24075, it was going to require O(50-100) GB to load a single run. Peak basics is available, it's just calculating the peak_shadow I guess.

**Comment by WenzDaniel** [comment]
I doubt that unless there is a bug. Is `peak_positions` available too? At least for v6 it is not. I just looked at `peak_basics` which is 2.2 GB and `peak_positions` should be smaller I think. So there is no way that these two data_types require 50 - 100 GB memory if they are both available.

**Comment by ershockley** [comment]
I guess it's during the computation of peak_shadow that we hit extreme memory consumption (not during loading of the lower level data)? Did you try yourself? Both @skazama and I hit this problem

**Comment by WenzDaniel** [comment]
But do you agree that if you load two data_types which are in total less than 10 GB it should not occupy 100 GB unless there is a bug in code? I am not arguing that I do not believe you that the memory consumption is so high. All I want to say that making it a save_when.ALWAYS plugin does not solve the issue. It sounds like a bug to me.

**Comment by WenzDaniel** [comment]
I am sorry, but I cannot confirm to observe the high memory consumption for 24075. I processed `peak_shadow` for `024075`, `peak_basics` was stored and `peak_positions` was not (but the individual pos rec data_types were stored.) `peak_basics` and `peak_positions` have a size of 2219 MB and 1638 MB respectively. See attached image:

example

I also did some additional checks. I compared things with the previous straxen v1.2.8
for which my memory consumption was slightly smaller around 2 GB - 3 GB during processing. I compared the output data_types of the old and new plugin version and its byte-size doubled which explains the lower amount of memory before.

**Comment by ershockley** [comment]
We were doing `st.get_df(runid, 'event_shadow')`. I think this loads all of peak_shadow into memory, whereas `st.make` handles memory better? Or am I misunderstanding?

What we are trying to do is have `peak_shadow` be written to disk always, rather than explicitly as you are doing, so that you don't have to go out of your way to call `st.make` before `st.get_df`. But maybe i'm wrong.

**Comment by WenzDaniel** [comment]
Okay let me check with get_df still sounds like a bug to me. I checked the number of bytes of the peak_shadow data_type which is 88 per row and compared it to peaklets which was something like 3100ish. Peaklets for  `24075` was about 118 GB. So peakshaodws should be actually below 10 GB. But, I must admit I am not working a lot with DataRames I prefer the numpy.structured arryas. So might be that some funky is going on like converting everything to 64 bit for the dataframe.

**Comment by skazama** [comment]
sorry @WenzDaniel, do you think we can merge this PR or should wait a bit to investigate potential dataframe bugs?

**Comment by JoranAngevaare** [comment]
@skazama @ershockley @WenzDaniel I must admit that I think what you observed is simply because you tried loading the data when much lower level processing was still ongoing. Specifically the neural nets can take a large amount of memory.
afbeelding


By the way this is not what is happening (you clear peak_shadow from your memory as soon as it's processed up to `event_shadow`)
> We were doing st.get_df(runid, 'event_shadow'). I think this loads all of peak_shadow into memory, whereas st.make handles memory better? Or am I misunderstanding?

I don't think that loading in a dataframe can cause a memory usage that is that high (you only buffer each of the chunks output of `event_shadow`). When I made 8k runs last friday, it was super easy to compute.

**Review by JoranAngevaare — COMMENTED** [review]
@dachengx I think the explicit saving of the peaks info is fine, could you revert that? I would definitely approve on removing the explicit saving at the events level, there is a clear speed benefit to be gained from not having to load so much data at that level

**Comment by WenzDaniel** [comment]
@JoranAngevaare can you reproduce the error? I simply cannot and I real would like to understand whats going wrong here.

**Comment by WenzDaniel** [comment]
>  I must admit that I think what you observed is simply because you tried loading the data when much lower level processing was still ongoing

This is/was my suspicion too. But according to the others the low level data was already stored.

**Comment by JoranAngevaare** [comment]
So for this specific - very high rate run - I can definitely imagine that if peak_basics is stored but the pos-rec algo's are not, it's going to take a lot of resources. 
afbeelding

I'll double check the memory, but the plugin does take some time to compute (since it's a very high rate run)

**Review by JoranAngevaare — APPROVED** [review]

**Comment by dachengx** [comment]
> @dachengx I think the explicit saving of the peaks info is fine, could you revert that? I would definitely approve on removing the explicit saving at the events level, there is a clear speed benefit to be gained from not having to load so much data at that level

Hey. I just reverted it.

**Comment by JoranAngevaare** [comment]
@WenzDaniel , I've checked but the max usage for this run was ~6.5 GB:
afbeelding

**Comment by ershockley** [comment]
Hmm okay something weird is going on then, because both Shingo and I could load the other event-level data for this run just fine, it was just the event_shadow giving problems. But good if it is fine now

**Pull request merged**
