### PR TITLE
automatically appending local rucio path

### PR DESCRIPTION
**Pull request by FaroutYLq**
## What does the code in this PR do / what does it improve?
Liberate users from manually adding midway rucio RSE by specifying 
```python
st_midway = cutax.xenonnt_online(_rucio_local_path='/project/lgrandi/rucio', include_rucio_local = True)
```

## Can you briefly describe how it works?
Introduced a new parameter in `xenonnt_online` called `_auto_append_rucio_local`. If True (by default it is True), it will make `include_rucio_local = True` and append the midway rucio path in `_rucio_local_path`.  

## Can you give a minimal working example (or illustrate with a figure)?
After modification, `st = cutax.xenonnt_online()` will have access to data in midway rucio if you are not on dali compute nodes.

_Please include the following if applicable:_
  - [x] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### CODE REVIEW

**Comment by FaroutYLq** [comment]
This is just a dirty workaround. The proper way to do it will require decoupling hardcoding in `straxen.RunDB`. For example: [here](https://github.com/XENONnT/straxen/blob/0aeb68347071e61f4e88b628dec62fbb6f3334f5/straxen/storage/rundb.py#L127-L137).

**Comment by FaroutYLq** [comment]
Meanwhile, we should probably also refactor `_rucio_local_path`. It has been marked "Only use for testing!" for a while...

**Comment by dachengx** [comment]
Whether we want to merge it like this depends on whether we want to postpone the complete decoupling of dali in straxen's hardcode.

**Review by dachengx — APPROVED** [review]
Thanks @FaroutYLq . 

`st = straxen.contexts.xenonnt_online()`

On dali computing node, storages are:
```
[straxen.storage.rundb.RunDB, readonly: True,
 strax.storage.files.DataDirectory, readonly: True, path: /dali/lgrandi/xenonnt/raw, take_only: ('raw_records', 'raw_records_he', 'raw_records_aqmon', 'raw_records_nv', 'raw_records_aqmon_nv', 'raw_records_aux_mv', 'raw_records_mv'),
 strax.storage.files.DataDirectory, readonly: True, path: /dali/lgrandi/xenonnt/processed,
 strax.storage.files.DataDirectory, readonly: True, path: /project2/lgrandi/xenonnt/processed,
 strax.storage.files.DataDirectory, readonly: True, path: /project/lgrandi/xenonnt/processed,
 strax.storage.files.DataDirectory, path: ./strax_data]
```

On xenon1t computing node, storages are:
```
[straxen.storage.rundb.RunDB, readonly: True,
 strax.storage.files.DataDirectory, readonly: True, path: /dali/lgrandi/xenonnt/raw, take_only: ('raw_records', 'raw_records_he', 'raw_records_aqmon', 'raw_records_nv', 'raw_records_aqmon_nv', 'raw_records_aux_mv', 'raw_records_mv'),
 strax.storage.files.DataDirectory, readonly: True, path: /dali/lgrandi/xenonnt/processed,
 strax.storage.files.DataDirectory, readonly: True, path: /project2/lgrandi/xenonnt/processed,
 strax.storage.files.DataDirectory, readonly: True, path: /project/lgrandi/xenonnt/processed,
 strax.storage.files.DataDirectory, path: ./strax_data,
 straxen.storage.rucio_local.RucioLocalFrontend, readonly: True, path: /project/lgrandi/rucio/]
```

Looks good to me.

**Comment by FaroutYLq** [comment]
Since we are having [tutorial](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:analysis:analysis_tools_team:midway3_rucio_guide#how_should_i_define_my_context) for users to load data now, I feel less urgency to do this dirty workaround. Personally I suggest in straxen we do things technically better rather than quick dirty tricks like what I did. I would turn this into draft again now. Thanks @dachengx

**Comment by FaroutYLq** [comment]
@dachengx . I discussed with @jingqiangye yesterday and we think for now the user experience might be more important than software logic elegancy. Let's reconsider merging this for the coming environment release.

**Comment by dachengx** [comment]
> @dachengx . I discussed with @jingqiangye yesterday and we think for now the user experience might be more important than software logic elegancy. Let's reconsider merging this for the coming environment release.

No objection. Just keep in mind that this will anyway take effect after the new release of nT `base_environment`.

**Comment by FaroutYLq** [comment]
Yes I am aware. Thanks for the head up

Lanqing Yuan

On Jun 10, 2023, at 1:24 PM, Dacheng Xu ***@***.***> wrote:

﻿

@dachengx<https://github.com/dachengx> . I discussed with @jingqiangye<https://github.com/jingqiangye> yesterday and we think for now the user experience might be more important than software logic elegancy. Let's reconsider merging this for the coming environment release.

No objection. Just keep in mind that this will anyway take effect after the new release of nT base_environment.

**Pull request merged**
