### PR TITLE
track if rucio is active

### PR DESCRIPTION
**Pull request by jorana**
## What does the code in this PR do / what does it improve?
Tweak #472, only init the remove backend if rucio is installed

## Can you briefly describe how it works?
Keep track of a flag, if that is false, don't use the remove

### CODE REVIEW

**Comment by jorana** [comment]
what is this stuff with codefactor lately that it starts complaining about unrelated code 😞 ?

**Review by ershockley — APPROVED** [review]
Thanks Joran! Beat me to it :)

**Comment by ershockley** [comment]
Ugh, I just tried merging master into this guy and testing failed again...

**Comment by jorana** [comment]
> 
> 
> Ugh, I just tried merging master into this guy and testing failed again...

🤦 yeah I should have kept this a draft, I knew this would happen for we introduced a new context and I changed the * import in the context-test suite. Recently codefactor has been complaining about some issues that aren't actually related to a given PR which is slightly annoying (see my comment above).

**Pull request merged**
