### PR TITLE
Update matplotlib_utils.py

### PR DESCRIPTION
**Pull request by GiovanniVolta**
Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible

**What is the problem / what does the code in this PR do**
I would like to have the chance to save the PMT arrays picture

**Can you briefly describe how it works?**
I have added "save" variable which default value is False. If it is True the function return the figure

### CODE REVIEW

**Comment by WenzDaniel** [comment]
While it does not hurt, I am also not sure if this is strictly needed. You can always get the last figure via 
```
fig = plt.gcf()  # gcf means get current figure
```
And then save it.

**Comment by GiovanniVolta** [comment]
Ok, let me close the PR then

**Comment by jorana** [comment]
I'm also not sure if I understand. What would not work that you would like to do with the syntax below?
```python
import straxen
import numpy as np
import matplotlib.pyplot as plt
straxen.plot_pmts(np.arange(494))
plt.savefig('test.png')
```

**Comment by GiovanniVolta** [comment]
That wasn't working for me. The picture was empty. Sure there was some error, but Daniel's one worked at the first attempt. My PR was useless

**Comment by WenzDaniel** [comment]
I would not say it was useless, the `plt.gca` and `plt.gcf` are a bit hidden features of matplotlib. Maybe we should add it to the doc strings at least.

**Comment by jorana** [comment]
> That wasn't working for me. The picture was empty. 

This usually happens when you `plt.show()` before `plt.savefig('test.png')`

**Pull request closed without merging**
