### PR TITLE
Release v 0 12 5

### PR DESCRIPTION
**Pull request by WenzDaniel**
**What is the problem / what does the code in this PR do**
New release v0.12.5

### CODE REVIEW

**Review by jorana — CHANGES_REQUESTED** [review]
Please update the requirements for strax first

**Comment by WenzDaniel** [comment]
Okay, also changed the corresponding tag. I will add this step to our "How-to".

**Comment by jorana** [comment]
> Okay, also changed the corresponding tag. I will add this step to our "How-to".
Thanks, this is not always required though, only if we induce incompatibility on the strax side.

**Review by jorana — APPROVED** [review]
Travis will fail but that is ok. We can rerun after strax is released.

**Pull request merged**
