### PR TITLE
modified corrected_area

### PR DESCRIPTION
**Pull request by Jianyu010**
_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

Modified CorrectedArea to enable partitioned TPC (AB and CD).

## Can you briefly describe how it works?

Added `partitions_event.py` under `plugins` directory. Then it is called in `event_processing.py` and used in `CorrectedArea`

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

### CODE REVIEW

**Comment by Jianyu010** [comment]
I am not sure what the output of `straxen.URLConfig` is... Please checkout [here](https://github.com/XENONnT/straxen/blob/3171cb38c44726843456c6c0481bf19ffcac31b5/straxen/plugins/event_processing.py#L719). The use is pretty straightforward if my understanding of this function is correct.

**Comment by JoranAngevaare** [comment]
Hi Jianyu, thanks for the PR! If I understand the gist correctly, you want to add the functionality to allow a position dependent correction? Would it in that case perhaps make sense [to make a map ](https://github.com/XENONnT/straxen/blob/partitioned_TPC/straxen/itp_map.py#L59) out of it (@l-althueser ?). This would require less hard-coding and make it simpler to update and maintain?

**Comment by l-althueser** [comment]
I guess we need something in between. We want to have like a map but with per run time dependence. So we might need a file with arbitrary volume definitions that works well with per run numbers or such.

**Comment by Jianyu010** [comment]
@JoranAngevaare This is more treating two partitions of the TPC differently in dealing with time dependent corrections. The note can be found [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=jlong:sr0_2_region_se_correction). A hard coded partitioning is needed for the moment.

**Pull request closed without merging**
