### PR TITLE
Speed up event pattern fit

### PR DESCRIPTION
**Pull request by WenzDaniel**
## What does the code in this PR do / what does it improve?
There was a request to improve the performance of our event_pattern_fit-plugin. With the proposed changes the speed increases by a factor of three. See also attached images.

## Can you briefly describe how it works?
I profiled the performance of the compute method of the plugin and found binomial_test to be the bottleneck. To increase the performance I numbafied the corresponding functions and created some numbafiable scipy-functions based on their cython implementations.  The new bottleneck is now given by `neg2llh_modpoisson`. However, any attempt to increase its performance failed.  

kr83m_run_event_pattern_fit
binom_test_imporved

### CODE REVIEW

**Comment by terliuk** [comment]
Do we have a check of pattern fit before and after this change? as we do not expect any changes and outputs should be exactly the same, right?

**Comment by WenzDaniel** [comment]
> Do we have a check of event pattern fit values before and after this change? as we do not expect any changes and outputs should be exactly the same, right?

I compared results before and after the speed up and the out put was identical. I have not tested Giovanni's fixes though. (But I thing here the results do change, do not they?)

**Comment by jorana** [comment]
Thanks all involved, is this ready for merging?

**Comment by WenzDaniel** [comment]
From my side yes. But I think @GiovanniVolta wanted to make some simplifications.

**Comment by GiovanniVolta** [comment]
Sorry guys, let me do one last check. I want to be sure everything is fine for the binomial test.

**Comment by GiovanniVolta** [comment]
It looks like everything is fine. The accepted fraction is higher because we fixed [few bugs](https://github.com/XENONnT/straxen/issues/629) in the p-value calculation.

PR_S1AFT

For me, we can proceed with the merge.

**Pull request merged**
