### PR TITLE
Numbafy function

### PR DESCRIPTION
**Pull request by WenzDaniel**
_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?
In this PR we are speeding up the peak bayes classifer using numba. The basics logic of the code is still the same. I just moved `np.linspace` in front of the loop and used numba friendly buffers (np.zeros) instead of append.

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Just for completeness below is the code profiling for 5 min of calibration data before/after the change:
bayes_classifier_vanilla
bayes_classifier_numba

I also checked whether we can do something for the `compute_inference` function, but the slowest part of the code is given by those two lines https://github.com/XENONnT/straxen/blob/84dc673495441bb7b308e25e9f3493351ed6a0aa/straxen/plugins/bayes_peak_classification.py#L132-L133

which cannot really be optimized any further.

**Comment by WenzDaniel** [comment]
One more thing for completeness there seems to be a small numerical difference in the computed quantiles between the two versions of the code. I do not know exactly where it is coming from though. For the computed waveforms it is fine.

quantiels_numeric_issue

**Comment by JoranAngevaare** [comment]
Nice work, seems like a 6x speedup?


One question:
>which cannot really be optimized any further.

Isn't there something we can do for the 100-iterations for loop in the line you mentioned ([straxen/straxen/plugins/bayes_peak_classification.py](https://github.com/XENONnT/straxen/blob/84dc673495441bb7b308e25e9f3493351ed6a0aa/straxen/plugins/bayes_peak_classification.py#L132-L133))

I can imagine the many slicing-steps can be written in a more effective way?

**Comment by ahiguera-mx** [comment]
Hi @WenzDaniel 
Thanks a lot for looking at this, I don't have any issue with the changes, the small difference is coming from `np.cumsum()` maybe numba an numpy use different precision (dtypes).
Also for my own education I remove the nested loop and put it in a separate function and got the same performance time-wise, so I guess numba does all the magic.
 @tinapeters Do you have any comment?

**Review by ahiguera-mx — APPROVED** [review]

**Comment by WenzDaniel** [comment]
> I can imagine the many slicing-steps can be written in a more effective way?

If you have an idea please let me know. I tried a few things to numbafy this loop, but there was not any performance increase. My impression was that compute the log over so many values simply takes time and there is not anything we can do.

**Comment by JoranAngevaare** [comment]
> > I can imagine the many slicing-steps can be written in a more effective way?
> 
> If you have an idea please let me know. I tried a few things to numbafy this loop, but there was not any performance increase. My impression was that compute the log over so many values simply takes time and there is not anything we can do.

Sure, I could have a try but consider it unlikely that I will fix it, could I re-use your notebook? Is it e.g. on analysiscode?

**Pull request merged**
