### PR TITLE
allow dynamic copy of dtype

### PR DESCRIPTION
**Pull request by jorana**
**What is the problem / what does the code in this PR do**
See XENONnT/straxen#353

**Can you briefly describe how it works? & Can you give a minimal working example (or illustrate with a figure)?**
See https://github.com/AxFoundation/strax/pull/395

**Prerequisites**
https://github.com/AxFoundation/strax/pull/395

### CODE REVIEW

**Comment by GiovanniVolta** [comment]
It looks okay to me. It should not have an impact on the computation but maybe is better if I try it or did you already try it?

**Review by WenzDaniel — APPROVED** [review]
Looks, good to me thanks again. About the performance: Yes we add a little overhead but should be negligible as long as you are not copying just single value. At least this would be my guess.

**Comment by jorana** [comment]
In fact, it should be faster than it used to be @GiovanniVolta . Previously, this was done without numba which slower (depends also little on your machine).

afbeelding

# Here is the full example, the number of n_copy did not change the factor ~3 I got here
```python
import numba
import strax
import numpy
import numpy as np

def copy_unjitted(records, raw_records):
    for d in ('time', 'length', 'dt', 'channel', 'pulse_length', 'record_i', 'baseline', 'data'):
        records[d] = raw_records[d]
        
n_copy = 100000
rr = np.ones(n_copy, dtype=strax.raw_record_dtype())
r = np.empty(n_copy, dtype=strax.record_dtype())

print(f'Using {rr.nbytes/1e9} GB rr and {r.nbytes/1e9} GB records')


%%timeit
copy_unjitted(r, rr)

%%time
strax.copy_to_buffer(rr, r, "_test_r_to_buffer")

%%timeit
strax.copy_to_buffer(rr, r, "_test_r_to_buffer")

%load_ext memory_profiler
%memit copy_unjitted(r, rr)

%memit strax.copy_to_buffer(rr, r, "_test_r_to_buffer")
```

**Comment by GiovanniVolta** [comment]
Perfect! Thank you guys!

**Pull request merged**
