### PR TITLE
Adding correction of Z position due to non-uniform drift velocity

### PR DESCRIPTION
**Pull request by terliuk**
## What does the code in this PR do / what does it improve?
Adds correction of Z position bias due to non-uniform field and, correspondingly, drift velocity. 

## Can you briefly describe how it works?
It loads a map produced from COMSOL field simulation. The map gets r_naive, z_naive and returns expected bias value that is then subtracted from z_naive. 

Map is uploaded to database in this PR https://github.com/XENONnT/private_nt_aux_files/pull/251

## Can you give a minimal working example (or illustrate with a figure)?
```
st.get_array(runid, ["event_positions"])
```
the new corrected position is in field `z_dv_corr`

### CODE REVIEW

**Review by jingqiangye — APPROVED** [review]
Hey I did a test and it looks good, see [Fig. 5](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:terliuk:drift_field_z_bias_correction).

**Comment by jingqiangye** [comment]
Thanks for the explanation @terliuk ! I like the current improvement and also the future plan. I have no objection to the current name unless someone has a better idea. However, the automatic tests still failed today complaining about the absence of the file but I think it was uploaded to the database yesterday. Any idea?

**Comment by dachengx** [comment]
> Thanks for the explanation @terliuk ! I like the current improvement and also the future plan. I have no objection to the current name unless someone has a better idea. However, the automatic tests still failed today complaining about the absence of the file but I think it was uploaded to the database yesterday. Any idea?

`EventPositions` is registered in the 1T context when auto-test. But it has no default map for 1T. We should add a legacy placeholder for 1T, like here:
https://github.com/XENONnT/straxen/blob/83ede84027855ba172db124165f61c66042073f1/straxen/plugins/events/event_positions.py#L47

**Comment by dachengx** [comment]
@jingqiangye If the testing codes still exist, would you please test the performance again to make sure I did not write anything wrong?

**Review by dachengx — APPROVED** [review]
Looks good to me.

**Review by jingqiangye — APPROVED** [review]
@dachengx thanks for fixing this! I just tested with another run and don't see any problem.

**Comment by jingqiangye** [comment]
Thanks @terliuk for the nice PR and @dachengx for fixing the auto test. I will merge this now.

**Pull request merged**
