### PR TITLE
Event Positions bug corrected z

### PR DESCRIPTION
**Pull request by cfuselli**
## What does the code in this PR do / what does it improve?
the same z_obs variable was returned twice, now changed to z_cor

## Can you give a minimal working example (or illustrate with a figure)?

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

### CODE REVIEW

**Review by WenzDaniel — APPROVED** [review]
Oh wow thanks for spotting. Can you sent in slack tech-support a plot z/z_naive versus r**2 to show the difference of the two parameters. We should make people aware.

**Comment by l-althueser** [comment]
No, the z_obs was the one intended! :)

**Comment by l-althueser** [comment]
We should leave a comment there but we actually changed to z_obs since the z correction with FDC was found to be not working correctly and should not be used until fixed (which might never happen). I will find the PR and link here

**Comment by l-althueser** [comment]
See https://github.com/XENONnT/straxen/issues/527

**Comment by WenzDaniel** [comment]
Do you mind to open another PR putting a comment? I agree that it is quite dangerous right now to be mistaken as a bug.

**Comment by cfuselli** [comment]
Oh, I see! Nevermind!

**Pull request closed without merging**
