### PR TITLE
Accelerate Euclidean distance by numba

### PR DESCRIPTION
**Pull request by dachengx**
_Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible_

## What does the code in this PR do / what does it improve?

Nothing is changed numerically.

## Can you give a minimal working example (or illustrate with a figure)?

```
import os
from memory_profiler import memory_usage
import numpy as np
import numba
import matplotlib.pyplot as plt
import strax
import cutax


home = os.path.expanduser('~')
st = cutax.xenonnt_offline(xedocs_version='global_v16')
run_id = '050775'
st.storage = [strax.DataDirectory(os.path.join(home, f'{run_id}/input'), readonly=True)]

PeakletClassificationSOM0 = st.get_single_plugin(run_id, 'peaklet_classification')
peaklets = st.get_array(run_id, 'peaklets', chunk_number={'peaklets': 0}, progress_bar=False)

def compute():
    PeakletClassificationSOM0.compute(peaklets)

mem = memory_usage(proc=compute, interval=0.1, timestamps=True)
mem = np.array(mem)

fig, ax = plt.subplots(1, 1, figsize=(4, 3))
ax.plot(mem[:, 1] - mem[0, 1], mem[:, 0] / 1e3, color='black', lw=0.5)
ax.set_xlabel('Time [s]')
ax.set_ylabel('Memory usage [GB]')

fig.savefig('peaklet_classification.svg', transparent=True, dpi=800)
plt.close(fig)
```

The improvement is visible:
image

_Please include the following if applicable:_
  - [ ] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [ ] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

### _Notes on testing_
 - _Until the automated tests pass, please mark the PR as a draft._
 - _On the XENONnT fork we test with database access, on private forks there is no database access for security considerations._

All _italic_ comments can be removed from this template.

### CODE REVIEW

**Comment by LuisSanchez25** [comment]
This looks really promising! Do you know what the speed impact would be here? Is this implementation faster than cdist?

**Comment by LuisSanchez25** [comment]
Looks good to me, let me just do some quick tests to make sure we get the same numbers for both methods

**Comment by LuisSanchez25** [comment]
I have a quick question since I don't seem to be able to get the function to run locally since numba seems to reject using the assert function, did you not run into this error? The error goes away when using @numba.jit(nopython=True, cache=True) instead

**Comment by dachengx** [comment]
> I have a quick question since I don't seem to be able to get the function to run locally since numba seems to reject using the assert function, did you not run into this error? The error goes away when using @numba.jit(nopython=True, cache=True) instead

My gut feeling is that the discrepancy is from different numba versions. But anyway, I moved the asssert out.

**Comment by LuisSanchez25** [comment]
Ok then other than that I think everything looks good!

**Pull request merged**
