### PR TITLE
Added support of dill for resource files

### PR DESCRIPTION
**Pull request by terliuk**
Before you submit this PR: make sure to put all operations-related information in a wiki-note, a PR should be about code and is publicly accessible

**What is the problem / what does the code in this PR do**
Adds support for dill files in resources in `get_resource`/`open_resource` functions

**Can you briefly describe how it works?**
Usage is identical to pickle files
**Can you give a minimal working example (or illustrate with a figure)?**

Please include the following if applicable:
  - Update the docstring(s)
  - Update the documentation
  - Tests to check the (new) code is working as desired.
  - Does it solve one of the open issues on github?

Please make sure that all automated tests have passed before asking for a review (you can save the PR as a draft otherwise).

### CODE REVIEW

**Comment by terliuk** [comment]
Previously, it was not possible to store some of the scipy objects in pickle. In particular, `RegularGridInterpolator`. However, I checked now and it looks like now it works with standard pickle. I think it can still be useful, but up to you to decide.

**Comment by jorana** [comment]
@terliuk , looks fine to me, only codefactor has some security issues (like it has for pickle), would you say we need to worry about these?

**Comment by terliuk** [comment]
In general, it the future it is better if we use dedicated formats, but i am not sure how realistic it is. My understanding is that dill/pickle does full serialization, so technically can contain malicious binary code/class inside. So given that we use pickle already, it shouldn't lead to new concerns in addition to pickle ones.

**Comment by jorana** [comment]
Right, sure, I think that summarizes it quite nicely. In the file-repos, we highly discourage the usage of such files, however supporting them in principle may not hurt. We should try depending on them as little as possible but e.g. dedicated scripts may benefit from this utility function. Otherwise people just `import dill` and do it manually.

**Pull request merged**
