### PR TITLE
Another update to CorrectedAreas: Use CMT tuples instead of URLConfigs

### PR DESCRIPTION
**Pull request by ershockley**
## What does the code in this PR do / what does it improve?
Same thing as #817, but doesn't use URLConfigs as they are interfering with CMT-related functions like `apply_global_version`, `get_cmt_options`, etc. I think maybe the switch to URLConfigs should wait until CMT2.0, unfortunately :/ 

I will use #817 to instead start switching everythning to URLConfigs, and we can maybe merge it later on along with #816. 

## Can you briefly describe how it works?
It's yet another attempt to get this `tcs2` variable in, but this time using the tuple CMT configs instead of the new URLConfig.

### CODE REVIEW

**Comment by jmosbacher** [comment]
@ershockley sorry you had to rewrite this, are you are sure its not an easy fix? see PR #820 for possible fixes for the `apply_global_version` and `get_cmt_options`, did you notice any other incompatibilities besides those two functions?

BTW you dont have to revert to using strax.Option to use the old CMT configs, the URLConfig is backward compatible so you should be able to set it to a CMT tuple for now and then switching in the future wont require changing the plugin.

**Comment by ershockley** [comment]
Thanks @jmosbacher, let me see if that PR will help #817. 

And I spent much less time writing this than struggling with the test suite so it is fine ;)

**Comment by ershockley** [comment]
The tests are passing now in #817 thanks to Yossi's help, so I think we probably don't need this one anymore.

**Comment by JoranAngevaare** [comment]
okay, I'll close this PR

**Pull request closed without merging**
